// Dev sample: a pure-concept lesson built from viz scenes — exercises the
// `viz` tool end-to-end in the real Player (?sample=viz). Not baked; no audio,
// so scenes pace by autoAdvanceMs and the timer clock drives the animation.
export const lesson = {
  slug: 'viz-demo',
  title: 'Why momentum escapes local minima',
  subtitle: 'A pure-concept lesson driven by the 3b1b viz tool',
  library: 'optimization',
  throughline: 'inertia',
  persona: 'devreel',
  accent: '#58C4DD',
  workspace: { files: {} },
  scenes: [
    {
      id: 's1',
      chapter: 'The landscape',
      narration: 'A loss function is a landscape: two valleys, and the right one is **deeper**.',
      say: 'A loss function is a landscape. This one has two valleys, and the one on the right is deeper.',
      focus: 'viz',
      action: { tool: 'viz', animation: 'gradient-descent', act: 'the loss landscape' },
      autoAdvanceMs: 4000,
    },
    {
      id: 's2',
      chapter: 'The problem',
      narration: 'Plain gradient descent follows `−∇f` into the *nearest* valley — and stays there.',
      say: 'Plain gradient descent follows the negative gradient into the nearest valley. And it stays there.',
      focus: 'viz',
      action: { tool: 'viz', animation: 'gradient-descent', act: 'gradient descent' },
      autoAdvanceMs: 4500,
    },
    {
      id: 's3',
      chapter: 'The fix',
      narration: 'Momentum keeps **velocity** between steps — enough to carry it over the ridge.',
      say: 'Momentum keeps velocity between steps. Watch it carry enough speed to sail over the ridge into the deeper valley.',
      focus: 'viz',
      action: { tool: 'viz', animation: 'gradient-descent', act: 'momentum' },
      autoAdvanceMs: 4500,
    },
    {
      id: 's4',
      chapter: 'The nuance',
      narration: 'Adam adapts step sizes — fast and smooth, but adaptivity alone does **not** escape.',
      say: 'Adam adapts its step sizes in every direction. It converges fast and smooth. But adaptivity alone does not escape local minima.',
      focus: 'viz',
      action: { tool: 'viz', animation: 'gradient-descent', act: 'Adam' },
      autoAdvanceMs: 4500,
    },
    {
      id: 's5',
      chapter: 'The takeaway',
      narration: 'Same start, same gradients — three different fates.',
      say: 'Same start. Same gradients. Three different fates.',
      focus: 'viz',
      action: { tool: 'viz', animation: 'gradient-descent', act: 'compare' },
      autoAdvanceMs: 4000,
    },
  ],
}
